# Requisição para criar um novo usuário (signup)
POST http://localhost:8080/api/v1/usuarios/signup
Content-Type: application/json

{
  "firstName": "Logan",
  "lastName": "Cardoso",
  "email": "logancardoso@gmail.com",
  "tipoUsuario": "Administrador",
  "idiomaPreferido": "pt",
  "password": "123123123"
}

###

# Requisição para login do usuário
POST http://localhost:8080/api/v1/usuarios/login
Content-Type: application/json

{
  "email": "logancardoso@gmail.com",
  "password": "123123123"
}

###

# Requisição para obter um usuário específico (autenticado)
# Substitua {token} pelo token JWT obtido após o login
GET http://localhost:8080/api/v1/usuarios/{id}
Authorization: Bearer {token}

###

# Requisição para atualizar informações do usuário (autenticado)
# Substitua {token} pelo token JWT obtido após o login
PUT http://localhost:8080/api/v1/usuarios/{id}
Content-Type: application/json
Authorization: Bearer {token}

{
  "firstName": "Logan",
  "lastName": "Almeida Cardoso",
  "tipoUsuario": "Administrador",
  "idiomaPreferido": "en"
}

###

# Requisição para deletar um usuário (deleção lógica, autenticado)
# Substitua {token} pelo token JWT obtido após o login
DELETE http://localhost:8080/api/v1/usuarios/a759ab96-9603-41d1-9b99-3d3b83065f2e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxvZ2FuY2FyZG9zb0BnbWFpbC5jb20iLCJyb2xlIjoiQWRtaW5pc3RyYWRvciIsImF1ZCI6ImFwaS1jbGllbnQiLCJleHAiOjE3Mjc1NDY3ODQsImlzcyI6ImJvaS1tYXJyb256aW5oby1hcGkifQ.hUr76dQ4eWAzY1k2qzS0dwAi0Vyr04QC1jw-wI0q-M8
